"""Single source of truth for scanner metadata.

Every other script reads from here. To add a scanner:
    1. Add an entry to SCANNERS below.
    2. (Optional) Add an extractor in extract_detail.py.
    3. (Optional) Add a render function in inject_renderers.py.
    4. Run rebuild_report.py.

Schema:
    - mode: "static" | "dynamic"
    - stack: "main" | "specialized" | "exclude" | "broken"
"""
from __future__ import annotations
from dataclasses import dataclass, field

@dataclass(frozen=True)
class Scanner:
    name: str
    mode: str
    type: str
    author: str
    license: str
    repo: str
    since: str = ""
    covers: tuple[str, ...] = ()
    what: str = ""
    how: str = ""
    when: str = ""
    pros: str = ""
    cons: str = ""
    alts: str = ""
    stack: str = "main"
    is_original: bool = False


SCANNERS: dict[str, Scanner] = {
    # ─── Original 14 (already in HTML; metadata here for STACKS computation) ─
    "syft":       Scanner("syft", "static", "SBOM", "Anchore", "Apache-2.0",
                          "https://github.com/anchore/syft", "2021",
                          covers=("sbom",), is_original=True),
    "trivy":      Scanner("trivy", "static", "Vuln (CVE+IaC+secrets+misconfig)",
                          "Aqua Security", "Apache-2.0",
                          "https://github.com/aquasecurity/trivy", "2019",
                          covers=("cve","iac","secrets","misconfig","sbom"), is_original=True),
    "grype":      Scanner("grype", "static", "Vuln (CVE)", "Anchore", "Apache-2.0",
                          "https://github.com/anchore/grype", "2020",
                          covers=("sbom","cve"), is_original=True),
    "dockle":     Scanner("dockle", "static", "Container Linter", "goodwithtech",
                          "Apache-2.0", "https://github.com/goodwithtech/dockle",
                          "2019", covers=("misconfig",), is_original=True),
    "trufflehog": Scanner("trufflehog", "static", "Secret (verificado)",
                          "Truffle Security", "AGPL-3.0",
                          "https://github.com/trufflesecurity/trufflehog",
                          covers=("secrets",), is_original=True),
    "gitleaks":   Scanner("gitleaks", "static", "Secret (regex)", "Zachary Rice",
                          "MIT", "https://github.com/gitleaks/gitleaks",
                          covers=("secrets",), is_original=True, stack="specialized"),
    "clamav":     Scanner("clamav", "static", "Antivírus", "Cisco Talos", "GPLv2",
                          "https://www.clamav.net/", "2002",
                          covers=("malware",), is_original=True, stack="specialized"),
    "whatweb":    Scanner("whatweb", "dynamic", "Web Fingerprint", "urbanadventurer",
                          "GPLv3", "https://github.com/urbanadventurer/WhatWeb",
                          covers=("fingerprint",), is_original=True, stack="exclude"),
    "nmap":       Scanner("nmap", "dynamic", "Network Scanner",
                          "Gordon Lyon (Fyodor)", "NPSL", "https://nmap.org/", "1997",
                          covers=("network","fingerprint"), is_original=True),
    "nikto":      Scanner("nikto", "dynamic", "Web Vuln (legado)", "Chris Sullo",
                          "GPLv2", "https://github.com/sullo/nikto",
                          covers=("web","misconfig"), is_original=True, stack="exclude"),
    "nuclei":     Scanner("nuclei", "dynamic", "Web Vuln (templates)",
                          "ProjectDiscovery", "MIT",
                          "https://github.com/projectdiscovery/nuclei",
                          covers=("web","cve","misconfig"), is_original=True),
    "wapiti":     Scanner("wapiti", "dynamic", "Web Vuln (DAST)", "Nicolas Surribas",
                          "GPLv2", "https://github.com/wapiti-scanner/wapiti",
                          covers=("web",), is_original=True, stack="exclude"),
    "zap":        Scanner("zap", "dynamic", "Web App (DAST + proxy)", "OWASP",
                          "Apache-2.0", "https://www.zaproxy.org/",
                          covers=("web",), is_original=True),
    "sqlmap":     Scanner("sqlmap", "dynamic", "SQLi especializado",
                          "Bernardo Damele · Miroslav Stampar", "GPLv2",
                          "https://sqlmap.org/", "2006",
                          covers=("web",), is_original=True, stack="specialized"),

    # ─── Phase 2: scanners adicionados que cobrem sinal único ───────────
    "openvas":        Scanner("openvas", "dynamic", "Network Vuln (NASL)", "Greenbone",
                          "GPLv2", "https://www.openvas.org/", "2005",
                          covers=("network","cve"),
                          what="Greenbone Vulnerability Manager. 100k+ plugins NASL. Equivalente open-source ao Nessus.",
                          how="Stack: GVM-Daemon + Manager + GSA web UI + scanner OpenVAS. Plugins NASL (~100k) cobrem CVE checks, brute force, default creds, banner grab.",
                          when="Scan periódico de fleets internos (PCI-DSS, ISO 27001).",
                          pros="Cobertura imensa de CVEs em serviços de rede. Padrão em compliance.",
                          cons="Setup pesado: bootstrap + sync de feed leva 20-30 min. Scan completo ~39 min para um alvo.",
                          alts="Nessus (commercial), Tenable.io, Qualys, Rapid7 InsightVM."),
    "osv":            Scanner("osv", "static", "Vuln (OSV.dev)", "Google", "Apache-2.0",
                          "https://github.com/google/osv-scanner", "2022",
                          covers=("cve","sbom"),
                          what="Scanner que casa pacotes contra a base OSV.dev — agregador de advisories ecosystem-native.",
                          how="Lê SBOMs/imagens via tarball; consulta osv.dev REST API para cruzar versão→advisory ID.",
                          when="Cobre Go modules, Rust crates, Cargo onde NVD costuma ficar atrás.",
                          pros="DB ecosystem-native. Mantida pelo Google.",
                          cons="Coverage menor de SO packages vs Trivy/Grype.",
                          alts="Trivy (mais amplo), Grype (CVE-only)."),
    "secretscanner":  Scanner("secretscanner", "static", "Secrets (container)",
                          "Deepfence", "Apache-2.0",
                          "https://github.com/deepfence/SecretScanner", "2020",
                          covers=("secrets",),
                          what="Scanner de secrets focado em containers. ~140 regras YARA-style.",
                          pros="Container-native, sem precisar exportar FS.",
                          cons="Binário precisa AVX2 — falha em CPUs antigas.",
                          alts="TruffleHog, GitLeaks, Whispers.", stack="broken"),
    "yara":           Scanner("yara", "static", "Malware/pattern", "VirusTotal",
                          "BSD-3", "https://github.com/VirusTotal/yara", "2007",
                          covers=("malware",),
                          what="Engine genérico de pattern-matching para classificar binários e textos.",
                          pros="Extensível com regras próprias. Padrão da indústria malware-research.",
                          cons="Rules precisam ser escritas/curadas.",
                          alts="ClamAV (signature-only), Capa.", stack="specialized"),
    "detect-secrets": Scanner("detect-secrets", "static", "Secrets (baseline)",
                          "Yelp", "Apache-2.0",
                          "https://github.com/Yelp/detect-secrets", "2018",
                          covers=("secrets",),
                          what="Scanner de secrets baseline-diffable — emite JSON de estado atual e diff contra runs futuros.",
                          pros="Modelo baseline reduz noise drastically.",
                          cons="Não verifica live. Plugins podem ter FP altos.",
                          alts="TruffleHog, GitLeaks, Whispers."),
    "guarddog":       Scanner("guarddog", "static", "Supply-chain malware",
                          "Datadog", "Apache-2.0",
                          "https://github.com/DataDog/guarddog", "2022",
                          covers=("supplychain",),
                          what="Detecta supply-chain malice em pacotes npm/PyPI.",
                          pros="Único scanner do stack focado em malice (não vulnerabilidade).",
                          cons="Limitado a npm e PyPI.",
                          alts="Phylum, Snyk Advisor.", stack="broken"),
    "govulncheck":    Scanner("govulncheck", "static", "Vuln Go (reachability)",
                          "Google (Go team)", "BSD-3",
                          "https://go.dev/blog/vuln", "2022",
                          covers=("cve",),
                          what="Scanner de CVE para Go com reachability analysis.",
                          pros="Único scanner reachability-aware no stack.",
                          cons="Só Go.",
                          alts="Trivy, Grype.", stack="specialized"),
    "clair":          Scanner("clair", "static", "Vuln (CVE per layer)",
                          "Red Hat / Quay", "Apache-2.0",
                          "https://github.com/quay/clair", "2015",
                          covers=("cve",),
                          what="Scanner CVE com arquitetura layer-by-layer indexed.",
                          pros="Layer-indexing dedup natural em registries.",
                          cons="clair-action standalone exige DB pré-baixado.",
                          alts="Trivy, Grype.", stack="broken"),
    "dependency-check": Scanner("dependency-check", "static", "Vuln (CPE matching)",
                          "OWASP", "Apache-2.0",
                          "https://github.com/dependency-check/DependencyCheck", "2012",
                          covers=("cve",),
                          what="OWASP Dependency-Check: motor de correlação CPE-based contra NVD.",
                          pros="OWASP project. NVD + OSS Index dual-feed.",
                          cons="Lento (download NVD ~30+ min).",
                          alts="Snyk, Trivy.", stack="broken"),
    "cdxgen":         Scanner("cdxgen", "static", "SBOM (OWASP)",
                          "OWASP CycloneDX", "Apache-2.0",
                          "https://github.com/CycloneDX/cdxgen", "2021",
                          covers=("sbom",),
                          what="Gerador SBOM CycloneDX 1.5 multi-language com VEX support.",
                          pros="Coverage profunda em Maven/Gradle/Bazel.",
                          cons="Requer toolchain do build instalada.",
                          alts="Syft, Microsoft SBOM Tool.", stack="broken"),
    "retire":         Scanner("retire", "static", "Vuln JS (hash/version)",
                          "Erlend Oftedal", "Apache-2.0",
                          "https://github.com/RetireJS/retire.js", "2013",
                          covers=("cve",),
                          what="retire.js: detecta libs JS vulneráveis casando hash/version dos arquivos .js.",
                          pros="Detecta libs vendored fora do dependency manifest.",
                          cons="Só JS client-side.",
                          alts="Trivy, npm audit, Snyk."),
    "whispers":       Scanner("whispers", "static", "Secrets (configs)",
                          "Adam Listek", "Apache-2.0",
                          "https://github.com/adeptex/whispers", "2019",
                          covers=("secrets",),
                          what="Whispers: parser de configs estruturados (YAML/JSON/Dockerfile).",
                          pros="Structured-aware: menos FP que regex em YAML/JSON.",
                          cons="Sensibilidade alta gera ruído.",
                          alts="TruffleHog, GitLeaks, detect-secrets.", stack="specialized"),
    "kube-linter":    Scanner("kube-linter", "static", "K8s manifest issues",
                          "StackRox / Red Hat", "Apache-2.0",
                          "https://github.com/stackrox/kube-linter", "2020",
                          covers=("misconfig",),
                          what="StackRox kube-linter: lint de YAMLs Kubernetes para best practices.",
                          pros="K8s-specific.",
                          cons="Skip silently se imagem não traz YAML.",
                          alts="Trivy, Checkov, Polaris.", stack="broken"),
    "hadolint":       Scanner("hadolint", "static", "Dockerfile lint",
                          "Lukas Martinelli", "MIT",
                          "https://github.com/hadolint/hadolint", "2015",
                          covers=("misconfig",),
                          what="Hadolint: linter de Dockerfile com regras de boas-práticas e shellcheck.",
                          pros="Shellcheck nas RUNs detecta classes de bugs únicos.",
                          cons="Reconstrução via history perde COPY/ADD targets.",
                          alts="Dockle, Trivy --scanners config."),
    "checkov":        Scanner("checkov", "static", "IaC misconfig",
                          "Bridgecrew / Prisma", "Apache-2.0",
                          "https://github.com/bridgecrewio/checkov", "2019",
                          covers=("iac","misconfig"),
                          what="Checkov: 1000+ políticas de IaC + Dockerfile + SCA misconfig.",
                          pros="Coverage maior que Trivy/Dockle.",
                          cons="Heavy: 700MB image.",
                          alts="Trivy, tfsec, KICS."),
    "pip-audit":      Scanner("pip-audit", "static", "Vuln Python (PyPA)",
                          "PyPA", "Apache-2.0",
                          "https://github.com/pypa/pip-audit", "2022",
                          covers=("cve",),
                          what="pip-audit: scanner de CVE Python autoritativo (PyPA Advisory DB).",
                          pros="Autoridade direta (PyPA).",
                          cons="Só Python.",
                          alts="Safety, Snyk, Trivy.", stack="broken"),
    "httpx":          Scanner("httpx", "dynamic", "Web fingerprint",
                          "ProjectDiscovery", "MIT",
                          "https://github.com/projectdiscovery/httpx", "2020",
                          covers=("fingerprint","web"),
                          what="httpx: prober web fast — fingerprint, TLS, JARM, CDN.",
                          pros="Fast. Multi-feature em um binário.",
                          cons="Apenas fingerprint, não scan de vulns.",
                          alts="WhatWeb, Wappalyzer."),
    "jaeles":         Scanner("jaeles", "dynamic", "Web Vuln (signatures)",
                          "j3ssie", "MIT",
                          "https://github.com/jaeles-project/jaeles", "2019",
                          covers=("web",),
                          what="Jaeles: scanner web template-driven, similar a Nuclei.",
                          pros="Template-driven.",
                          cons="Comunidade menor que Nuclei.",
                          alts="Nuclei, Wapiti.", stack="broken"),
    "arachni":        Scanner("arachni", "dynamic", "Web App (DAST)", "Sarosys",
                          "Arachni Public Source",
                          "https://github.com/Arachni/arachni", "2010",
                          covers=("web",),
                          what="Arachni: framework Ruby DAST com checks profundos para SQLi/XSS/RFI/LFI.",
                          pros="Suite completa similar a ZAP.",
                          cons="Projeto archived (último release 2017).",
                          alts="OWASP ZAP, Burp Suite, Wapiti."),
    "testssl":        Scanner("testssl", "dynamic", "TLS/SSL audit", "Dirk Wetter",
                          "GPLv2", "https://github.com/drwetter/testssl.sh", "2014",
                          covers=("network",),
                          what="testssl.sh: auditoria abrangente de TLS/SSL via OpenSSL.",
                          pros="Mais detalhado que Nessus/OpenVAS para TLS.",
                          cons="Targets HTTP retornam baseline 'no TLS'.",
                          alts="sslyze, sslscan, Qualys SSL Labs.", stack="specialized"),
}


def by_stack(stack: str) -> list[str]:
    return sorted([s.name for s in SCANNERS.values() if s.stack == stack])


def by_mode(mode: str, exclude_broken: bool = True) -> list[str]:
    return sorted([s.name for s in SCANNERS.values()
                   if s.mode == mode and (not exclude_broken or s.stack != "broken")])
